### ISSUE TITLE
qterminal doesn't save some preferences after closing

### ISSUE THREAD

**Issue by sgomezc** [qterminal/qterminal#138]
After closing qterminal, preferences are not saved in qterminal.ini, It seems that preferences are reload with default values each time. I have tried to save this file with custom preferences but its changed when program starts again. 

Just to clarify a bit more, some preferences are not saved like hide tab bar and transparency.

Unless I am wrong I assume that this instructions

``` c

    appTransparency = settings.value("MainWindow/ApplicationTransparency", 0).toInt();
    termTransparency = settings.value("TerminalTransparency", 0).toInt();

    hideTabBarWithOneTab = settings.value("HideTabBarWithOneTab", false).toBool();

```
are always applied

**Comment by worblehat** [comment]
There already is pull request #136 that should fix the problem.

**Comment by yweweler** [comment]
For me, the latest Git version still shows this behavior.

**Comment by worblehat** [comment]
The mentioned pull request is still open.

**Comment by sgomezc** [comment]
Hi worblehat, after moving to your branch "settings-persistancy" i see that the problem persists with the same kind of preferences. There must be another problem with preferences at startup which are being overwriting by its default values.

**Comment by sgomezc** [comment]
Thanks worblehat, 

problem is solved after moving to settings-persistancy branch.

**Comment by jleclanche** [comment]
Fixed by 397259e
